# Generated by Django 3.0.8 on 2020-07-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calciatori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calciatore',
            name='contratto',
            field=models.PositiveSmallIntegerField(choices=[(0, 'svincolato'), (1, 'con_contratto')], default=0),
        ),
    ]
