# Generated by Django 3.0.8 on 2020-07-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calciatori', '0002_calciatore_contratto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calciatore',
            old_name='contratto',
            new_name='status',
        ),
    ]
