# Generated by Django 3.0.8 on 2020-07-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('is_gruppo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'artista',
                'verbose_name_plural': 'artisti',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'genere',
                'verbose_name_plural': 'generi',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=256)),
                ('anno_pubblicazione', models.IntegerField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musica.Artista')),
                ('genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musica.Genere')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'album',
                'ordering': ('titolo',),
            },
        ),
    ]
