# Generated by Django 3.0.8 on 2020-07-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'dieta',
                'verbose_name_plural': 'diete',
            },
        ),
        migrations.AlterModelOptions(
            name='alimento',
            options={'verbose_name': 'alimento', 'verbose_name_plural': 'alimenti'},
        ),
        migrations.AlterModelOptions(
            name='tipologia',
            options={'verbose_name': 'tipologia', 'verbose_name_plural': 'tipologie'},
        ),
        migrations.AddField(
            model_name='alimento',
            name='diete',
            field=models.ManyToManyField(to='alimenti.Dieta'),
        ),
    ]
