# Generated by Django 3.0.8 on 2020-07-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimenti', '0003_auto_20200714_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='is_animale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alimento',
            name='is_vegetale',
            field=models.BooleanField(default=False),
        ),
    ]
