# Generated by Django 3.0.8 on 2020-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimenti', '0004_auto_20200714_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'ordering': ('nome',), 'verbose_name': 'alimento', 'verbose_name_plural': 'alimenti'},
        ),
        migrations.AlterModelOptions(
            name='tipologia',
            options={'ordering': ('nome',), 'verbose_name': 'tipologia', 'verbose_name_plural': 'tipologie'},
        ),
        migrations.AddField(
            model_name='alimento',
            name='calorie',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
